import XModalForm from '@/components/ProComponents/XModalForm';
import { apiApiKeyCreate, apiApiKeyUpdate } from '@/services/account';
import { t } from '@/services/i18nRuntime';
import type { ApiKeyInfo } from '@/types/interfaces/account';
import {
  ProFormDatePicker,
  ProFormRadio,
  ProFormText,
} from '@ant-design/pro-components';
import { Form, message } from 'antd';
import dayjs from 'dayjs';
import React, { useEffect } from 'react';

interface ApiKeyFormModalProps {
  /** 弹窗显隐状态 */
  open: boolean;
  /** 显隐状态变更回调 */
  onOpenChange: (open: boolean) => void;
  /** 编辑模式下的行数据；若为空则为新建模式 */
  record?: ApiKeyInfo;
  /** 提交成功回调 */
  onSuccess: () => void;
}

/**
 * API Key 创建与编辑表单弹窗
 */
const ApiKeyFormModal: React.FC<ApiKeyFormModalProps> = ({
  open,
  onOpenChange,
  record,
  onSuccess,
}) => {
  const [form] = Form.useForm();
  const isEdit = !!record;

  useEffect(() => {
    if (open) {
      if (isEdit) {
        // 转换回显：后端返回的是格式化字符串 (如 YYYY-MM-DD HH:mm:ss)
        // 日期选择器需要 YYYY-MM-DD 格式
        const expire =
          record.expire &&
          record.expire !== '0000-00-00 00:00:00' &&
          dayjs(record.expire).isValid()
            ? dayjs(record.expire).format('YYYY-MM-DD')
            : undefined;

        form.setFieldsValue({
          name: record.name,
          expire,
          accessKey: record.accessKey,
          status: record.status,
        });
      } else {
        // 新建模式重置表单
        form.resetFields();
        form.setFieldsValue({ status: 1 }); // 默认启用
      }
    }
  }, [open, record, isEdit, form]);

  const onFinish = async (values: any) => {
    try {
      const { name, status, expire: expireVal } = values;
      // 这里的 expireVal 是日期选择器返回的字符串（YYYY-MM-DD）
      // 若为空则传 null
      const expire = expireVal ? dayjs(expireVal).valueOf() : null;

      if (isEdit) {
        // 调用更新接口
        await apiApiKeyUpdate({
          accessKey: record.accessKey,
          name,
          status,
          expire,
        });
        message.success(t('PC.Pages.ApiKeyFormModal.updateSuccess'));
      } else {
        // 调用创建接口
        await apiApiKeyCreate({
          name,
          expire,
        });
        message.success(t('PC.Pages.ApiKeyFormModal.createSuccess'));
      }
      onSuccess(); // 成功后执行列表刷新等操作
      return true;
    } catch (error) {
      // 报错由全局 request 拦截器处理
      return false;
    }
  };

  return (
    <XModalForm
      title={
        isEdit
          ? t('PC.Pages.ApiKeyFormModal.editTitle')
          : t('PC.Pages.ApiKeyFormModal.createTitle')
      }
      open={open}
      onOpenChange={onOpenChange}
      form={form}
      onFinish={onFinish}
      width={520}
    >
      <ProFormText
        name="name"
        label={t('PC.Pages.ApiKeyFormModal.keyName')}
        placeholder={t('PC.Pages.ApiKeyFormModal.keyNamePlaceholder')}
        fieldProps={{ maxLength: 50, showCount: true }}
        rules={[
          {
            required: true,
            message: t('PC.Pages.ApiKeyFormModal.enterKeyName'),
          },
          { max: 50, message: t('PC.Pages.ApiKeyFormModal.enterKeyName') },
        ]}
      />

      <ProFormDatePicker
        name="expire"
        label={t('PC.Pages.ApiKeyFormModal.expireTime')}
        placeholder={t('PC.Pages.ApiKeyFormModal.expireTime')}
        tooltip={t('PC.Pages.ApiKeyFormModal.expireTimeTooltip')}
      />

      {isEdit && (
        <>
          <ProFormText
            name="accessKey"
            label={t('PC.Pages.ApiKeyFormModal.apiKey')}
            placeholder={t('PC.Pages.ApiKeyFormModal.autoGenerated')}
            disabled
          />
          <ProFormRadio.Group
            name="status"
            label={t('PC.Pages.ApiKeyFormModal.status')}
            options={[
              {
                label: t('PC.Pages.ApiKeyFormModal.statusEnabled'),
                value: 1,
              },
              {
                label: t('PC.Pages.ApiKeyFormModal.statusDisabled'),
                value: 0,
              },
            ]}
          />
        </>
      )}
    </XModalForm>
  );
};

export default ApiKeyFormModal;
